# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'

- checkout: self
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'

#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
